# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(924, 685)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(300)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(200)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayout.addWidget(self.tableWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 924, 26))
        self.menubar.setObjectName("menubar")
        self.menu_file = QtWidgets.QMenu(self.menubar)
        self.menu_file.setObjectName("menu_file")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionSelectDirectory = QtWidgets.QAction(MainWindow)
        self.actionSelectDirectory.setObjectName("actionSelectDirectory")
        self.actionSelectFiles = QtWidgets.QAction(MainWindow)
        self.actionSelectFiles.setObjectName("actionSelectFiles")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionStart = QtWidgets.QAction(MainWindow)
        self.actionStart.setObjectName("actionStart")
        self.actionStop = QtWidgets.QAction(MainWindow)
        self.actionStop.setEnabled(False)
        self.actionStop.setObjectName("actionStop")
        self.actionUpload = QtWidgets.QAction(MainWindow)
        self.actionUpload.setEnabled(False)
        self.actionUpload.setObjectName("actionUpload")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionSplitPdf = QtWidgets.QAction(MainWindow)
        self.actionSplitPdf.setObjectName("actionSplitPdf")
        self.menu_file.addAction(self.actionSelectDirectory)
        self.menu_file.addAction(self.actionSelectFiles)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.actionStart)
        self.menu_file.addAction(self.actionStop)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.actionUpload)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.actionQuit)
        self.menu.addAction(self.actionHelp)
        self.menu.addAction(self.actionAbout)
        self.menu_2.addAction(self.actionSplitPdf)
        self.menubar.addAction(self.menu_file.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.toolBar.addAction(self.actionSelectDirectory)
        self.toolBar.addAction(self.actionSelectFiles)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSplitPdf)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionStart)
        self.toolBar.addAction(self.actionStop)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionUpload)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionQuit)

        self.retranslateUi(MainWindow)
        self.actionQuit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "延安红云平台编辑辅助工具"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "文件名称"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "状态"))
        self.menu_file.setTitle(_translate("MainWindow", "文件(&F)"))
        self.menu.setTitle(_translate("MainWindow", "帮助(&H)"))
        self.menu_2.setTitle(_translate("MainWindow", "工具(&T)"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionSelectDirectory.setText(_translate("MainWindow", "选择目录"))
        self.actionSelectFiles.setText(_translate("MainWindow", "选择文件"))
        self.actionSelectFiles.setToolTip(_translate("MainWindow", "选择文件"))
        self.actionQuit.setText(_translate("MainWindow", "退出"))
        self.actionAbout.setText(_translate("MainWindow", "关于"))
        self.actionStart.setText(_translate("MainWindow", "开始转换"))
        self.actionStop.setText(_translate("MainWindow", "停止"))
        self.actionStop.setToolTip(_translate("MainWindow", "停止正在进行的任务"))
        self.actionUpload.setText(_translate("MainWindow", "上传"))
        self.actionUpload.setToolTip(_translate("MainWindow", "上传电子书到红云服务器"))
        self.actionHelp.setText(_translate("MainWindow", "帮助"))
        self.actionHelp.setToolTip(_translate("MainWindow", "使用说明和帮助"))
        self.actionSplitPdf.setText(_translate("MainWindow", "拆分PDF"))
        self.actionSplitPdf.setToolTip(_translate("MainWindow", "把一个大的PDF文件拆分成为几个小文件"))

